[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd services/license-api && npm install"]

[phases.build]
cmds = ["cd services/license-api && npm run build"]

[start]
cmd = "cd services/license-api && node dist/index.js"

