{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anvil-bot-chart.fullname" . }}-admin-secrets
  labels:
    {{- include "anvil-bot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
type: Opaque
data:
  # Values are base64 encoded
  jwtSecret: {{ .Values.admin.secrets.jwtSecret | b64enc | quote }}
  superAdminId: {{ .Values.admin.secrets.superAdminId | b64enc | quote }}
  superAdminEmail: {{ .Values.admin.secrets.superAdminEmail | b64enc | quote }}
  superAdminPassword: {{ .Values.admin.secrets.superAdminPassword | b64enc | quote }}
  superAdminName: {{ .Values.admin.secrets.superAdminName | b64enc | quote }}
{{- end }}
