{{- if and .Values.swap.enabled .Values.swap.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "anvil-bot-chart.fullname" . }}-swap
  labels:
    {{- include "anvil-bot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: swap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "anvil-bot-chart.fullname" . }}-swap
  minReplicas: {{ .Values.swap.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.swap.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.swap.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.swap.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.swap.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.swap.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
